### ISSUE TITLE
error trying to add this plugin

### ISSUE THREAD

**Issue by getarobo** [furo-org/ZMQUE#2]
```
LogPluginManager: Mounting plugin zmque
LogConfig: Setting CVar [[r.BloomQuality:5]]
LogConfig: Setting CVar [[r.BloomQuality:5]]
LogTemp: Warning: ZMQ LibraryPath:../../../../../../Users/gene/Documents/Unreal Projects/MyProject3/Plugins/ZMQUE/Binaries/ThirdParty/zmqLibrary/Win64/libzmq-mt-4_3_1.dll
CompilerResultsLog: zmqmod.cpp (0:00.84 at +0:00)
CompilerResultsLog: UE4Editor-zmque-0019.lib (0:00.11 at +0:00)
CompilerResultsLog:    Creating library C:\Users\gene\Documents\Unreal Projects\MyProject3\Plugins\ZMQUE\Intermediate\Build\Win64\UE4Editor\Development\zmque\UE4Editor-zmque-0019.lib and object C:\Users\gene\Documents\Unreal Projects\MyProject3\Plugins\ZMQUE\Intermediate\Build\Win64\UE4Editor\Development\zmque\UE4Editor-zmque-0019.exp
CompilerResultsLog: UE4Editor-zmque-0019.dll (0:00.34 at +0:01)
CompilerResultsLog:    Creating library C:\Users\gene\Documents\Unreal Projects\MyProject3\Plugins\ZMQUE\Intermediate\Build\Win64\UE4Editor\Development\zmque\UE4Editor-zmque-0019.suppressed.lib and object C:\Users\gene\Documents\Unreal Projects\MyProject3\Plugins\ZMQUE\Intermediate\Build\Win64\UE4Editor\Development\zmque\UE4Editor-zmque-0019.suppressed.exp
CompilerResultsLog: Error: LINK : fatal error LNK1181: cannot open input file 'C:\Users\gene\Documents\Unreal Projects\MyProject3\Plugins\ZMQUE\Intermediate\Build\Win64\UE4Editor\Development\zmque\UE4Editor-zmque.lib'
```

Hi, Im just trying to add zmq4.3.1 to ue4.26 on windows 10

Not sure where I am getting things wrong. I know its been awhile but do you have build.cs setting that I can try or updates? Thanks!

**Comment by yosagi** [comment]
Hi,

Add the zmque and zmqLibrary modules to your dependencies, and you're good to go.
Please refer to a simple project I've just created here (https://github.com/yosagi/zmqtest)
It can be compiled with UE4.26.2 on Windows 10.

Or my other project here (https://github.com/furo-org/CagePlugin) uses ZMQUE plugin from the other plugin.

I hope it helps.

**Comment by getarobo** [comment]
Hi @yosagi 

Thank you so much for zmqtest and example project. I was able to install get it up running but I had a problem with recving message from ZMQ_SUB socket . I based codes from https://github.com/furo-org/CagePlugin/blob/52080dca284e3bdaec5782b6241fddc479c8a19b/Source/Cage/Private/CommActor.cpp
```
// on constructor FImpl
ZContext = new zmq::context_t();
zmq::socket_t* subscriber = nullptr;
subscriber = new zmq::socket_t(*ZContext, ZMQ_SUB);
subscriber->connect("tcp://127.0.0.1:5571");
subscriber->setsockopt(ZMQ_SUBSCRIBE, "ue");

// on tick
zmq::message_t channel;
zmq::message_t msgbody;

int ret = D->subscriber->recv(&channel,ZMQ_DONTWAIT);

FString errorSTr(zmq_strerror(ret));
FString Str(channel.size(), (channel.data<char>()));

UE_LOG(LogTemp, Warning, TEXT("** zmq tick(%d)(%s)"), ret, *errorSTr);
/*
if (ret >= 0) {
//UE_LOG(LogTemp, Warning, TEXT("message (len=%d) received"), ret);

if (channel.more()) {
	// DONTWAITは不要? 非同期にする?
	ret = D->subscriber->recv(&msgbody, ZMQ_RCVMORE);
	//UE_LOG(LogTemp, Warning, TEXT("second part message (len=%d) received"), ret);
}

FString Str(msgbody.size(), (channel.data<char>()));
UE_LOG(LogTemp, Warning, TEXT("***AMyActorZMQ2 JOSN:%s"), *Str);

}
*/
```
gives me
```
LogTemp: Warning: ** zmq tick(-11)(Unknown error)
```


I was able to make a ZMQ_PUB and bind to *:54321 and send message and recv from differnt zmq app.
only part I am having problem is mutlipart message.

Do you have any ideas or adivces where to look for answers?

Thank you so much!

**Comment by getarobo** [comment]
Nevermind, I used original zmq.hpp and zmq_addon.hpp from cppzmq and it worked great!

Thank you so much you saved me!!!!!!!

**Comment by yosagi** [comment]
Is it possible to package your project with the original zmq.hpp? I modified zmq.hpp because I could not find a proper (or clean) way to package projects with a library throwing exceptions. So if it is possible, that is good news for me also.

**Comment by getarobo** [comment]
well, i used og way of handling error(exception) and it worked fine.
i made a copy form zmq.hpp & zmq_addon.hpp from cppzmq and named it zmq_ori.hpp, zmq_addon_ori.hpp and use these two instaed of zmq_nt.hpp.

for example
```
...
//#include "zmq_nt.hpp"
#include "zmq_ori.hpp"
#include "zmq_addon_ori.hpp"
...

zmq::context_t* ZContext = nullptr;
ZContext = new zmq::context_t();
ZContext->shutdown();


try {
   subscriber = new zmq::socket_t(*ZContext, zmq::socket_type::sub);
}
catch (const zmq::error_t& e) {
   int errornum = e.num();
   FString errorSTr(zmq_strerror(errornum));
   UE_LOG(LogTemp, Warning, TEXT("ZContext has shutdown, must spit out error (%s)"), *errorSTr);
   return;
}
```
gives me
```
LogTemp: Warning: ZContext has shutdown must be error found (Context was terminated)
```

**Comment by getarobo** [comment]
I just found out try catch aint way to go in Unreal (for packaging). will report if I find a way
